# This is a basic workflow to help you get started with Actions

name: Check code with ESlint and Prettier

on:
  pull_request:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checks out the latest Git commit
        uses: actions/checkout@v2
      - name: Sets up a Node.js environment
        uses: actions/setup-node@v2
      - run: npx eslint --ext .js,.react .
      - run: npx prettier --config .prettierrc.json -l "**/*.{js,react}"
